spring.profiles.active: h2
#로거
logging:
  pattern:
    console: '%-5level %logger{0} - %msg%n'
  level:
    root: info
    com.linor.singer.dao: trace
---
#데이타소스
spring: 
  profiles: postgres
  datasource:
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    password: spring1234
    url: jdbc:postgresql://localhost:5432/spring?currentSchema=singer
    username: spring

    #hikari Connection Pull 설정
    hikari:
      maximum-pool-size: 20
      idle-timeout: 1
      minimum-idle: 0

---
spring:
  profiles: h2
  datasource:
    platform: h2 
#    driver-class-name: org.h2.Driver
    initialization-mode: always

    #hikari Connection Pull 설정
    hikari:
      maximum-pool-size: 20
      idle-timeout: 1
      minimum-idle: 0
#    url: jdbc:h2:mem:test;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password: ''
  h2.console.enabled: true
