management:
  endpoint:
    health:
      show-details: always # when-authorized
    shutdown:
      enabled: true
  endpoints:
    web:
#      base-path: /app #디폴트 /actuator
      exposure:
        include: '*'
    
spring:
  security:
    user:
      name: admin
      password: secret
      roles:
      - ADMIN

info:
  app:
    name: Beginning Spring Boot 2
    description: This is a SpringBoot Demo app
    version: 1.0.0