#### 로그 설정
logging:
  level: 
    root: INFO
    com:
        linor: 
          app: TRACE
         
spring:
#데이타베이스 환경설정
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring?currentSchema=singer
    username: linor
    password: linor1234
    initialization-mode: always

  #Spring Batch 설정
  batch:
    #배치 데이타베이스 초기화(Spring Batch에 사용되는 테이블 생성)
    initialize-schema: always  
    job:
      #Bootstrap시 Job을 자동으로 실행하지 않도록 false로 함
      enabled: false

#마이바티스 설정
mybatis:
  mapper-locations: classpath*:/**/*Dao.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

files:
  input-file: files/input.csv
  output-file: files/output.csv      

