#사용 프로파일
spring.profiles.active: [postgres, dev]

#로거
logging:
  pattern:
    console: '%-5level %logger{0} - %msg%n'
  level:
    root: info
    com.linor.singer.dao: trace
---
#데이타소스
spring: 
  profiles: postgres
  datasource:
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring?currentSchema=singer
    username: linor
    password: linor1234
    initialization-mode: never

    #hikari Connection Pull 설정
#    hikari:
#      maximum-pool-size: 20
#      idle-timeout: 1
#      minimum-idle: 0

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create #create, create-drop, none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        physical-naming-strategy: com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy
        #format_sql: true
        #use_sql_comments: true
        jdbc.lob.non_contextual_creation: true
        #temp.use_jdbc_metadata_default: false
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

---
spring:
  profiles: h2
  datasource:
    platform: h2 
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password: ''
#    initialization-mode: always
#  h2.console.enabled: true

#    #hikari Connection Pull 설정
#    hikari:
#      maximum-pool-size: 20
#      idle-timeout: 1
#      minimum-idle: 0

  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.H2Dialect
#        format_sql: true
#        use_sql_comments: true
        physical-naming-strategy: com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy
#        max_fetch_depth: 3
#        jdbc.batch_size: 10
#        jdbc.patch_size: 50
      