#디폴트 프로파일
spring:
  profiles:
    active: 
      - init
      - dev

---
#마이바티스 설정
mybatis:
  mapper-locations: classpath*:/**/*Dao.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

---
#Spring Batch 설정
spring:
  batch:
    job:
      #Bootstrap시 Job을 자동으로 실행하지 않도록 false로 함
      enabled: false
      
input: input.csv
output: output.csv

---
#초기화 프로파일
spring:
  profiles: init

#데이타베이스 환경설정
  datasource:
    #데이타베이스 초기화(schema.sql, data.sql 실행)
    initialization-mode: always 
  batch:
    #배치 데이타베이스 초기화(Spring Batch에 사용되는 테이블 생성)
    initialize-schema: always  
---
#개발프로파일
spring:
  profiles: dev
  #데이타베이스 설정
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring?currentSchema=singer
    username: linor
    password: linor1234
    initialization-mode: always

#### 서버포트 설정
server:
  port: 8080
#### 로그 설정
logging:
  level: 
    root: INFO
    com:
        linor: 
          app: TRACE