server:
  servlet:
    context-path: /
  port: 8443
  ssl:
    enabled: true
    key-store: "classpath:keystore.p12"
    key-store-password: linor1111
    key-store-type: PKCS12
    key-alias: linor-ssl
    