logging:
  pattern:
    console: '%-5level %logger{0} - %msg%n'
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    password: spring1234
    url: jdbc:postgresql://localhost:5432/spring?currentSchema=singer
    username: spring

