spring:
  datasource:
    initialization-mode: always
    
#Multi DataSource 설정
db:
  db1: 
    datasource:
      driverClassName: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://localhost:5432/spring?currentSchema=new
      username: postgres
      password: postgres
      
  db2: 
    datasource:
      driverClassName: org.h2.Driver
      jdbcUrl: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS USERS
      username: sa
      password: sa
      
db1:
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        physical-naming-strategy: com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc.lob.non_contextual_creation: true
        temp.use_jdbc_metadata_default: false

db2:
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: none
        dialect: org.hibernate.dialect.H2Dialect
        physical-naming-strategy: com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy
        show_sql: true
        format_sql: true
        use_sql_comments: true
        