spring:
#데이타소스
  datasource:
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
    password: spring1234
    url: jdbc:postgresql://localhost:5432/spring?currentSchema=singer
    username: spring    

    #hikari Connection Pull 설정
    hikari:
      maximum-pool-size: 20
      idle-timeout: 1
      minimum-idle: 0

db:
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        physical-naming-strategy: com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy
        show_sql: false
        format_sql: true
        use_sql_comments: true
        jdbc.lob.non_contextual_creation: true
        temp.use_jdbc_metadata_default: false
