spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      
  session: #세션
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout: 60 #초단위
    
  datasource: #데이타소스
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/spring?currentSchema=singer
    username: linor
    password: linor1234
#    initialization-mode: always

    #hikari Connection Pull 설정
#    hikari:
#      maximum-pool-size: 20
#      idle-timeout: 1
#      minimum-idle: 0

  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        physical-naming-strategy: com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy
#        format_sql: true
#        use_sql_comments: true
        jdbc.lob.non_contextual_creation: true
        #temp.use_jdbc_metadata_default: false
